---
name: Build `get-release`

on:
  push:
    branches:
      - workflows
    paths:
      - 'get-release/*'
      - '!get-release/dist/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm and package
        working-directory: ${{ github.workspace }}/get-release
        run: |
          # Install npm, ncc and build
          npm install
          npm i -g @vercel/ncc
          npm run package
      - name: Push updated ncc build if available
        run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add get-release/dist/*
          if ! (git diff -s --staged --exit-code); then
            git commit -m "Build `get-release` for ${{ github.sha }}"
            git push
          fi
