name: Apply Patches

on:
  workflow_call:
    inputs:
      src-repo:
        description: "Source repo"
        required: true
        type: string
      version:
        description: "Version to apply patch"
        required: true
        type: string
      prerelease:
        description: "Is this a pre-release"
        required: true
        type: boolean
      repo:
        description: "Target repo"
        required: true
        type: string
      patch-repo:
        description: "Patch repo"
        required: true
        type: string
      patch-ref:
        description: "Patch ref"
        required: true
        type: string
    secrets:
      APP_PRIVATE_KEY:
        required: true
jobs:
  patch:
    name: Apply Patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.src-repo }}
          ref: ${{ inputs.version }}
          path: working
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.patch-repo }}
          ref: ${{ inputs.patch-ref }}
          path: patch
      - name: Split Repo
        env:
          REPO: ${{ inputs.repo }}
        id: split-repo
        run: |
            echo "owner=${REPO%%/*}" >> "$GITHUB_OUTPUT"
            echo "repo=${REPO#*/}" >> "$GITHUB_OUTPUT"
      - name: Get token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ steps.split-repo.outputs.owner }}
          repositories: ${{ steps.split-repo.outputs.repo }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Setup Git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
      # git commands like commit work using the bot user
      - run: |
          #git remote remove origin
          git remote set-url origin 'https://github.com/${{ inputs.repo }}.git'
          find "${{ github.workspace }}/patch/" -type f -iname *.patch -print0 | sort -z | xargs -r0 git am
          git tag -f ${{ inputs.version }}
          git push --force --tag
        working-directory: working
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repository: ${{ inputs.repo }}
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.prerelease }}